# Redis settings for deduplication
redis:
  host: "localhost"
  port: 6379
  db: 0
  deduplication_expiry: 86400  # 24 hours in seconds

# RSS feed sources mapped to their URLs
rss_feeds:
  # CNN: "http://rss.cnn.com/rss/cnn_topstories.rss"
  BBC: "http://feeds.bbci.co.uk/news/rss.xml"
  Fox News: "https://feeds.foxnews.com/foxnews/latest"
  The New York Times: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
  NPR: "https://www.npr.org/rss/rss.php?id=1001"

# Ingestion interval (in seconds)
ingestion:
  interval: 300  # 5 minutes
kafka:
  broker: "localhost:9092"
  topic: "news_articles"
  group_id: "streaming_pipeline_group"
  bootstrap_servers: "localhost:9092"
  user_behav_topic: "user_behavior_events"

nlp:
  spacy_model: "en_core_web_sm"
  embedding_model: "all-MiniLM-L6-v2"
  similarity_threshold: 0.8
processing:
  interval: 60

# MongoDB settings
mongo:
  host: "localhost"
  port: 27017
  db: "news_db"
  collections:
    articles: "articles"
    stories: "stories"
    user_interactions: "user_interactions"
    recommendations: "recommendations"

# Spark settings
spark:
  master: "local[*]"
  app_name: "news_recommendation_trainer"

# Model settings
model:
  recommendation:
    rank: 5
    iterations: 10
    reg_param: 0.1
  summarization:
    model_name: "sshleifer/distilbart-cnn-12-6"
    max_length: 150
    min_length: 50

training:
  interval: 3600

# Training settings
training:
  interval: 3600  # Seconds between training cycles (e.g., 1 hour)

faiss:
  index_file: "faiss_index.bin"
  mapping_file: "faiss_mapping.json"