# batch-cluster-refinement.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-cluster-refinement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-cluster-refinement
  template:
    metadata:
      labels:
        app: batch-cluster-refinement
    spec:
      containers:
      - name: batch-cluster-refinement
        image: your-registry/batch-cluster-service:latest  # Build and push your image
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: batch-cluster-service
spec:
  selector:
    app: batch-cluster-refinement
  ports:
  - port: 5000
    targetPort: 5000