# summarization-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarization-service
  template:
    metadata:
      labels:
        app: summarization-service
    spec:
      containers:
      - name: summarization-service
        image: your-registry/summarization-service:latest
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: summarization-service
spec:
  selector:
    app: summarization-service
  ports:
  - port: 5002
    targetPort: 5002